In [41]:
import numpy as np

In [42]:
X = np.random.rand(5, 5)
X

array([[0.04786024, 0.80114628, 0.31377452, 0.02375635, 0.75549467],
       [0.57338907, 0.14564244, 0.21769823, 0.81029364, 0.53764765],
       [0.66431645, 0.33540407, 0.78478095, 0.34221146, 0.68207189],
       [0.15317079, 0.52076838, 0.97999606, 0.7102689 , 0.45333269],
       [0.85482973, 0.65661538, 0.09015274, 0.01428434, 0.12928574]])

In [ ]:
X_mean = X.mean(axis=0)
X_mean

array([0.45871325, 0.49191531, 0.4772805 , 0.38016294, 0.51156653])

In [70]:
X_minus_mean = X - X_mean
X_minus_mean

array([[-0.41085302,  0.30923097, -0.16350598, -0.35640659,  0.24392814],
       [ 0.11467582, -0.34627287, -0.25958227,  0.4301307 ,  0.02608113],
       [ 0.2056032 , -0.15651124,  0.30750045, -0.03795148,  0.17050536],
       [-0.30554247,  0.02885307,  0.50271556,  0.33010596, -0.05823384],
       [ 0.39611647,  0.16470007, -0.38712776, -0.3658786 , -0.38228079]])

In [71]:
C = (X_minus_mean.T @ X_minus_mean) / (X.shape[0] -1)
C

array([[ 0.11862197, -0.03562806, -0.05157911, -0.01445964, -0.04895152],
       [-0.03562806,  0.06699577, -0.01451429, -0.07598759, -0.00623224],
       [-0.05157911, -0.01451429,  0.14781613,  0.06063534,  0.03112325],
       [-0.01445964, -0.07598759,  0.06063534,  0.13907887,  0.0096137 ],
       [-0.04895152, -0.00623224,  0.03112325,  0.0096137 ,  0.05969576]])

In [72]:
eigenval, eigenvec = np.linalg.eig(C)

idx = np.argsort(eigenval)[::-1]

eigenval_sorted = eigenval[idx]
eigenvec_sorted = eigenvec[:, idx]


print(f"EigenValues: {eigenval_sorted}\n\nEigenVectors: {eigenvec_sorted}")

EigenValues: [2.48028743e-01 1.72347285e-01 7.06389475e-02 4.11935201e-02
 9.61798620e-19]

EigenVectors: [[-0.3456995   0.63635768  0.4575241   0.32688043  0.39920126]
 [-0.24073817 -0.51514574  0.15494211 -0.35490992  0.7257423 ]
 [ 0.64462369 -0.19242525  0.73455626  0.07850762 -0.04118829]
 [ 0.59324958  0.47398633 -0.33440819 -0.35415887  0.43143313]
 [ 0.2346321  -0.26073597 -0.33950391  0.79724286  0.35511328]]


In [73]:
top_eigenvals = eigenval_sorted[:2]
top_eigenvecs = eigenvec_sorted[:, :2]

In [74]:
top_eigenvecs

array([[-0.3456995 ,  0.63635768],
       [-0.24073817, -0.51514574],
       [ 0.64462369, -0.19242525],
       [ 0.59324958,  0.47398633],
       [ 0.2346321 , -0.26073597]])

In [82]:
Xpca = X_minus_mean @ top_eigenvecs

In [83]:
Xpca

array([[-0.19201653, -0.6218185 ],
       [ 0.13767917,  0.4983818 ],
       [ 0.18231472,  0.08984706],
       [ 0.6049139 , -0.13438362],
       [-0.73289125,  0.16797327]])